name = "VeIR"
version = "0.1.0"
defaultTargets = ["veir-opt", "run-benchmarks", "Veir"]
testRunner = "Test"

[leanOptions]
experimental.module = true

[[lean_lib]]
name = "Veir"
root = "Veir"

[[lean_lib]]
name = "Test"
root = "Test"

[[lean_exe]]
name = "veir-opt"
root = "VeirOpt"

[[lean_exe]]
name = "run-benchmarks"
root = "RunBenchmarks"
