name = "VeIR"
version = "0.1.0"
defaultTargets = ["veir-opt", "run-benchmarks", "Veir"]
testRunner = "UnitTest"

[leanOptions]
experimental.module = true

[[lean_lib]]
name = "Veir"
root = "Veir"

[[lean_lib]]
name = "UnitTest"
root = "UnitTest"

[[lean_exe]]
name = "veir-opt"
root = "VeirOpt"

[[lean_exe]]
name = "run-benchmarks"
root = "RunBenchmarks"

[[lean_exe]]
name = "veir-interpret"
root = "VeirInterpret"
