name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          build-args: "--iofail"
          test: false

      - uses: leanprover/lean-action@v1
        with:
          build-args: "--iofail Veir"
          test: false

      - name: Create annotation for build error
        run: ls
      - name: Create annotation for build error
        run: pwd
      - name: Create annotation for build error
        run: ls /home/runner/work/veir/


      - uses: leanprover/lean-action@v1
        with:
          build-args: "--iofail Test"
          test: false
